// <auto-generated />
using System;
using JobTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504162010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTracker.Api.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PostingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("job_applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationDate = new DateOnly(2026, 5, 4),
                            Company = "Acme Consulting",
                            ContactName = "HR Team",
                            ContractType = "Apprendistato",
                            CreatedAtUtc = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Milano / Ibrido",
                            Notes = "Prima candidatura demo per verificare frontend e backend.",
                            PostingUrl = "https://example.com/jobs/dotnet-junior",
                            Role = "Junior .NET Developer",
                            SalaryMax = 30000m,
                            SalaryMin = 26000m,
                            Status = "Candidatura inviata",
                            UpdatedAtUtc = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationDate = new DateOnly(2026, 5, 2),
                            Company = "Northwind Tech",
                            ContractType = "Indeterminato",
                            CreatedAtUtc = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Remoto",
                            Notes = "Offerta demo con Angular e ASP.NET Core.",
                            PostingUrl = "https://example.com/jobs/full-stack",
                            Role = "Full Stack Developer",
                            SalaryMax = 38000m,
                            SalaryMin = 32000m,
                            Status = "Da valutare",
                            UpdatedAtUtc = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
